version: 2

defaults: &set_environment
  docker:
    - image: circleci/node:latest

step_restore_cache: &reastore_cache
  restore_cache:
    keys:
      - v1-dependencies-{{ checksum "yarn.lock" }}
      - v1-Dependencies

step_install_deps: &install_deps
  run:
    name: Install Dependencies
    command: yarn --frozen-lockfile


step_save_cache: &save_cache
  save_cache:
    paths:
      - ~/.cache/yarn
    key: v1-dependencies-{{ checksum "yarn.lock" }}

jobs:
  test:
    <<: *set_environment
    steps:
      - checkout
      - *restore_cache
      - *install_deps
      - *save_cache
      - run:
          name: Run Tests and Collect Coverage Reports
          command: yarn test:ci
      - store_artifacts:
          path: coverage